# Generated by Django 6.0.5 on 2026-06-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simple", "0002_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="screenshot",
            field=models.ImageField(blank=True, upload_to="screenshots/"),
        ),
    ]
