# Generated by Django 6.0.7 on 2026-07-12 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+\\d{1,4} [\\d ()/-]{3,20}$",
                                "Enter a dial code and number, e.g. '+49 171 1234567'.",
                            )
                        ],
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("us", "🇺🇸 United States"),
                            ("gb", "🇬🇧 United Kingdom"),
                            ("de", "🇩🇪 Germany"),
                            ("fr", "🇫🇷 France"),
                            ("es", "🇪🇸 Spain"),
                            ("it", "🇮🇹 Italy"),
                            ("nl", "🇳🇱 Netherlands"),
                            ("se", "🇸🇪 Sweden"),
                            ("pl", "🇵🇱 Poland"),
                            ("ca", "🇨🇦 Canada"),
                            ("br", "🇧🇷 Brazil"),
                            ("mx", "🇲🇽 Mexico"),
                            ("jp", "🇯🇵 Japan"),
                            ("kr", "🇰🇷 South Korea"),
                            ("cn", "🇨🇳 China"),
                            ("in", "🇮🇳 India"),
                            ("au", "🇦🇺 Australia"),
                            ("za", "🇿🇦 South Africa"),
                            ("ng", "🇳🇬 Nigeria"),
                        ],
                        default="",
                        max_length=2,
                    ),
                ),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="avatars/")),
                ("favourite_food", models.CharField(blank=True, default="", max_length=50)),
                (
                    "satisfaction",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
        ),
    ]
