# Generated by Django 6.0.4 on 2026-04-20 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutoSaveFormData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("message", models.TextField(blank=True, default="")),
                ("priority", models.CharField(default="low", max_length=20)),
                ("notify", models.CharField(default="email", max_length=20)),
                ("agree", models.BooleanField(default=False)),
                ("attachment", models.FileField(blank=True, upload_to="attachments/")),
            ],
        ),
        migrations.CreateModel(
            name="BasicFormData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(blank=True, default="")),
                ("priority", models.CharField(default="low", max_length=20)),
                ("notify", models.CharField(default="email", max_length=20)),
                ("agree", models.BooleanField(default=False)),
                ("attachment", models.FileField(blank=True, upload_to="attachments/")),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="e2e.region",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
