# Generated by Django 6.0.3 on 2026-03-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutoSaveFormData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("message", models.TextField(blank=True, default="")),
                ("priority", models.CharField(default="low", max_length=20)),
                ("notify", models.CharField(default="email", max_length=20)),
                ("agree", models.BooleanField(default=False)),
                ("attachment", models.FileField(blank=True, upload_to="attachments/")),
            ],
        ),
        migrations.CreateModel(
            name="BasicFormData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(blank=True, default="")),
                ("priority", models.CharField(default="low", max_length=20)),
                ("notify", models.CharField(default="email", max_length=20)),
                ("agree", models.BooleanField(default=False)),
                ("attachment", models.FileField(blank=True, upload_to="attachments/")),
            ],
        ),
    ]
