# Generated by Django 6.0.5 on 2026-06-06 15:11

import e2e.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e2e", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirtyTrackedData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, validators=[e2e.models._reject_legacy_bad])),
                ("email", models.EmailField(max_length=254)),
                ("note", models.TextField(blank=True, default="")),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("name", "LEGACY_BAD_CONSTRAINT"), _negated=True),
                        name="name_not_legacy_bad",
                    ),
                ],
            },
        ),
    ]
