# Generated by Django 6.0.5 on 2026-06-08 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e2e", "0002_dirtytrackeddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="dirtytrackeddata",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="e2e.region",
            ),
        ),
    ]
