# Generated by Django 6.0.5 on 2026-06-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e2e", "0003_dirtytrackeddata_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ConstraintPair",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("left", models.CharField(max_length=50)),
                ("right", models.CharField(max_length=50)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("left", "right"), name="uq_constraint_pair")],
            },
        ),
        migrations.CreateModel(
            name="UniquePair",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("left", models.CharField(max_length=50)),
                ("right", models.CharField(max_length=50)),
            ],
            options={
                "unique_together": {("left", "right")},
            },
        ),
    ]
