# Generated by Django 6.0.5 on 2026-06-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e2e", "0004_uniquecode_constraintpair_uniquepair"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatedCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(max_length=50, unique_for_date="published")),
                ("published", models.DateField()),
            ],
        ),
    ]
