# Generated by Django 6.0.5 on 2026-06-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e2e", "0006_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionalUnique",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(max_length=50)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("slug",),
                        name="uq_conditional_unique_active_slug",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomMessageUnique",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",),
                        name="uq_custom_message_unique_code",
                        violation_error_message="That code is already taken.",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UniqueAndCheckPair",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("left", models.CharField(max_length=50)),
                ("right", models.CharField(max_length=50)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("left", "right"), name="uq_unique_and_check_pair"),
                    models.CheckConstraint(
                        condition=models.Q(("left", "BAD"), _negated=True),
                        name="ck_unique_and_check_pair_left",
                    ),
                ],
            },
        ),
    ]
