# Generated by Django 6.0.5 on 2026-06-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e2e", "0007_conditionalunique_custommessageunique_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("left", models.CharField(max_length=50)),
                ("right", models.CharField(max_length=50)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("left", "BAD"), _negated=True), name="ck_multi_left"),
                    models.CheckConstraint(
                        condition=models.Q(("right", "BAD"), _negated=True),
                        name="ck_multi_right",
                        violation_error_code="right_is_bad",
                        violation_error_message="Right cannot be BAD.",
                    ),
                ],
            },
        ),
    ]
