# Generated by Django 6.0.5 on 2026-06-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e2e", "0008_multicheck"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckThenUnique",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("left", models.CharField(max_length=50)),
                ("right", models.CharField(max_length=50)),
                ("note", models.CharField(default="", max_length=50)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("note", "BAD"), _negated=True),
                        name="ck_check_then_unique_note",
                    ),
                    models.UniqueConstraint(fields=("left", "right"), name="uq_check_then_unique_pair"),
                ],
            },
        ),
    ]
