# Generated by Django 6.0.5 on 2026-07-13 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e2e", "0009_checkthenunique"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirtyUniquePair",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(max_length=50)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dirty_pairs",
                        to="e2e.region",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("region", "slug"), name="uq_dirty_unique_pair")],
            },
        ),
    ]
